server:
  port: 3001
spring:
  datasource:
    url: jdbc:mysql://localhost/ev_charging
    username: root
    password: root
  application:
    name: sellerMs
  cloud:
    consul:
      discovery:
        hostname: localhost
  jpa:
    hibernate:
      ddl-auto: update